### ISSUE TITLE
coref_kernels.so not found

### ISSUE THREAD

**Issue by MaudGoddefroy** [Filter-Bubble/e2e-Dutch#28]
Hi, 
I am trying to use your module as part of the stanza pipeline. Although the setup_all.sh does not exist (anymore), I think I installed it correctly. When I run the code as you propose under 'Quick start - Stanza', I get this error: 

Traceback (most recent call last):
  File "C:/Users/maudg/OneDrive/Documenten/SLT/stage/e2e_testing/testing.py", line 2, in <module>
    import e2edutch.stanza
  File "C:\Users\maudg\anaconda3\envs\e2e_testing\lib\site-packages\e2edutch\stanza.py", line 8, in <module>
    from e2edutch import coref_model as cm
  File "C:\Users\maudg\anaconda3\envs\e2e_testing\lib\site-packages\e2edutch\coref_model.py", line 13, in <module>
    from . import coref_ops
  File "C:\Users\maudg\anaconda3\envs\e2e_testing\lib\site-packages\e2edutch\coref_ops.py", line 8, in <module>
    pkg_resources.resource_filename("e2edutch", "coref_kernels.so"))
  File "C:\Users\maudg\anaconda3\envs\e2e_testing\lib\site-packages\tensorflow\python\framework\load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\maudg\anaconda3\envs\e2e_testing\lib\site-packages\e2edutch\coref_kernels.so not found

but when i look in that exact folder, it contains that so-file.
Does anyone know how to fixed that? Thank you in advance

**Comment by jiskattema** [comment]
It seems you are running windows, and we haven't tested this on windows (much?).
It could be related to windows specific loading of dynamic libraries; if you're willing to help us debug:

1. Replace 'coref_kernels.so' with 'coref_kernels.dll' in the following file:
```
File "C:\Users\maudg\anaconda3\envs\e2e_testing\lib\site-packages\e2edutch\coref_ops.py", line 8, in
pkg_resources.resource_filename("e2edutch", "coref_kernels.so"))
```

2. Copy (or rename) 'coref_kernels.so' to 'coref_kernels.dll' here:
```
C:\Users\maudg\anaconda3\envs\e2e_testing\lib\site-packages\e2edutch\coref_kernels.so
```

**Comment by MaudGoddefroy** [comment]
I applied both steps, but unfortunately this gives the same error: ...\e2edutch\coref_kernels.dll not found

**Comment by jiskattema** [comment]
Ok, thanks for trying and reporting. I'll try to see if we can reproduce this.

**Comment by dafnevk** [comment]
@MaudGoddefroy: Thanks for adressing this, and for pointing out the outdated documentation. 
Did you install the package with `pip install e2e-Dutch`  or by cloning the package and running `pip install .`?

It seems indeed that the package currently does not work on Windows. What I've found out so far:
- If you install with `pip install e2e-Dutch`, it fetches the compiled `coref_kernels.so` from pypi but it seems this doesn't work because the file was compiled on a different OS. The file thus need to be compiled locally (which should happen when running `python setup.py install` in this repository)
- That requires you to have a gcc compiler installed (see https://code.visualstudio.com/docs/cpp/config-mingw for instructions)
- But then I run into erros like `C:\Users\DafnevanKuppevelt\AppData\Local\Temp\cc58p3iy.o:coref_kernels.cc:(.text+0x30): undefined reference to 'tensorflow::OpKernel::OpKernel(tensorflow::OpKernelConstruction*)'` I have the idea that it doesn't link to tensorflow property, because `tf.get_link_flags()` (see [this line](https://github.com/Filter-Bubble/e2e-Dutch/blob/master/setup.py#L32) ) gives an empty list.
I don't know the solution for this, but I did find [this issue](https://github.com/tensorflow/tensorflow/issues/19122) where the TF developers admit a lack of documentation on that part.

I have to see when I have time to work on this more, it does not seem trivial so any help is appreciated.
Until then, I suggest you run the code in a Virtual Machine with Linux.
